#!/bin/bash
set -e

echo "=========================================================="
echo "🎬 TakeFive Dynamic FFmpeg Engine Builder"
echo "=========================================================="

# 1. Paths
BASE_DIR="$(pwd)"
SRC_DIR="${BASE_DIR}/src/ffmpeg"
OUT_DIR="${BASE_DIR}/takefive_prebuilt"
PREFIX="${OUT_DIR}/arm64"
DEPS_BASE_DIR="${OUT_DIR}/dependencies"

# 2. SDK Setup
SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
CC=$(xcrun --sdk iphoneos -f clang)
CXX=$(xcrun --sdk iphoneos -f clang++)

# 3. Dynamic Flag Processing
FFMPEG_EXTRA_FLAGS=()
FFMPEG_CFLAGS=("-arch arm64 -miphoneos-version-min=15.1")
FFMPEG_LDFLAGS=("-arch arm64 -miphoneos-version-min=15.1")

# Ensure deps dir exists
mkdir -p "${DEPS_BASE_DIR}"

# 4. FIX macOS DYLD FREEZE
# Exporting TMPDIR to a local path bypasses EndpointSecurity bugs on /var/folders
export TMPDIR="${BASE_DIR}/build_tmp"
mkdir -p "${TMPDIR}"

# Fetch all sources first
bash ./scripts/fetch_deps.sh

# 5. Fix FFmpeg Makefiles and scripts to bypass macOS execution bugs
bash ./patch_ffmpeg.sh

for arg in "$@"; do
  case $arg in
    --enable-*)
      LIB_NAME=$(echo $arg | sed 's/--enable-//')
      BUILD_SCRIPT="./scripts/build_${LIB_NAME}.sh"
      
      if [ -f "$BUILD_SCRIPT" ]; then
        echo "🔌 Injecting dependency: ${LIB_NAME}..."
        bash "$BUILD_SCRIPT"
        
        LIB_PATH="${DEPS_BASE_DIR}/${LIB_NAME}"
        FFMPEG_EXTRA_FLAGS+=("$arg")
        FFMPEG_CFLAGS+=("-I${LIB_PATH}/include")
        FFMPEG_LDFLAGS+=("-L${LIB_PATH}/lib")
        export PKG_CONFIG_PATH="${LIB_PATH}/lib/pkgconfig:${PKG_CONFIG_PATH}"
      else
        echo "⚠️  No build script found for ${LIB_NAME}, skipping..."
      fi
      ;;
  esac
done

# 4. Configure & Build FFmpeg
cd "${SRC_DIR}"
echo "⚙️  Configuring FFmpeg with injected flags: ${FFMPEG_EXTRA_FLAGS[*]}"

mkdir -p "${BASE_DIR}/build_tmp"
arch -arm64 env TMPDIR="${BASE_DIR}/build_tmp" bash ./configure \
    --prefix="${PREFIX}" \
    --enable-cross-compile \
    --target-os=darwin \
    --arch=arm64 \
    --sysroot="${SDK_PATH}" \
    --cc="${CC}" \
    --cxx="${CXX}" \
    --extra-cflags="${FFMPEG_CFLAGS[*]}" \
    --extra-ldflags="${FFMPEG_LDFLAGS[*]}" \
    --disable-programs --disable-doc --disable-debug --disable-asm \
    --enable-pic --enable-videotoolbox --enable-avfoundation --disable-audiotoolbox \
    --enable-small --enable-version3 --disable-shared --enable-static \
    --enable-filter=eq,colorbalance,scale,pad,setsar,fps,trim,setpts,atrim,asetpts,atempo,concat,anullsrc,aloop,volume,sidechaincompress,amix,aevalsrc,drawtext \
    "${FFMPEG_EXTRA_FLAGS[@]}" < /dev/null

make -j$(sysctl -n hw.ncpu)
make install

# ── Copy internal FFmpeg headers not installed by `make install` ──
# These are needed by the fftools source files included in the pod.
echo "📋 Copying internal FFmpeg headers..."

# libavutil internal headers
for h in thread.h internal.h libm.h getenv_utf8.h wchar_filename.h timer.h \
          attributes_internal.h cpu_internal.h dict_internal.h dynarray.h \
          ffmath.h file_open.h fixed_dsp.h float_dsp.h hwcontext_internal.h \
          imgutils_internal.h intmath.h mem_internal.h time_internal.h; do
  [ -f "${SRC_DIR}/libavutil/${h}" ] && cp "${SRC_DIR}/libavutil/${h}" "${PREFIX}/include/libavutil/${h}"
done

# libavutil/aarch64 internal headers (for arm64 timer)
mkdir -p "${PREFIX}/include/libavutil/aarch64"
[ -f "${SRC_DIR}/libavutil/aarch64/timer.h" ] && \
  cp "${SRC_DIR}/libavutil/aarch64/timer.h" "${PREFIX}/include/libavutil/aarch64/timer.h"

# libavcodec internal headers used by fftools
for h in mathops.h internal.h codec_internal.h decode.h encode.h packet_internal.h \
          thread.h threadframe.h options_table.h profiles.h; do
  [ -f "${SRC_DIR}/libavcodec/${h}" ] && cp "${SRC_DIR}/libavcodec/${h}" "${PREFIX}/include/libavcodec/${h}"
done

# libavformat internal headers
for h in os_support.h internal.h url.h avio_internal.h mux.h demux.h; do
  [ -f "${SRC_DIR}/libavformat/${h}" ] && cp "${SRC_DIR}/libavformat/${h}" "${PREFIX}/include/libavformat/${h}"
done

# libavfilter internal headers
for h in internal.h formats.h audio.h video.h filters.h framequeue.h framesync.h; do
  [ -f "${SRC_DIR}/libavfilter/${h}" ] && cp "${SRC_DIR}/libavfilter/${h}" "${PREFIX}/include/libavfilter/${h}"
done

# ── Generate config.h ──
# FFmpeg internal headers like libavutil/thread.h include "config.h". On macOS
# (case-insensitive FS), the React Native yoga Config.h would be found first via
# the CocoaPods all-target-headers hmap. We ship our own config.h so it wins.
echo "📋 Generating config.h for iOS arm64..."
BUILD_DATE=$(date +%Y%m%d)
cat > "${PREFIX}/include/config.h" << CONFIGEOF
/*
 * FFmpeg configuration for iOS arm64 (aarch64) — auto-generated by build_takefive.sh
 * This file must ship in the prebuilt tarball so CocoaPods finds it before yoga's Config.h.
 */
#ifndef FFMPEG_CONFIG_H
#define FFMPEG_CONFIG_H

#define FFMPEG_VERSION          "6.0"
#define FFMPEG_CONFIGURATION    "--target-os=darwin --arch=aarch64 --enable-static --disable-shared --enable-version3 --enable-libmp3lame --enable-libopenh264"
#define CC_IDENT                "Apple clang (iOS arm64)"
#define AVCONV_DATADIR          ""
#define FFMPEG_DATADIR          ""
#define ARCH_AARCH64             1
#define ARCH_ARM                 0
#define ARCH_X86                 0
#define ARCH_X86_64              0
#define HAVE_FAST_64BIT          1
#define HAVE_BIGENDIAN           0
#define HAVE_PTHREADS            1
#define HAVE_W32THREADS          0
#define HAVE_OS2THREADS          0
#define HAVE_THREADS             1
#define HAVE_PRCTL               0
#define HAVE_GETRUSAGE           1
#define HAVE_SETRLIMIT           0
#define HAVE_STRUCT_RUSAGE_RU_MAXRSS 1
#define HAVE_SYSCONF             1
#define HAVE_SYSCTL              1
#define HAVE_UNISTD_H            1
#define HAVE_SYS_RESOURCE_H      1
#define HAVE_SYS_SELECT_H        1
#define HAVE_TERMIOS_H           1
#define HAVE_IO_H                0
#define HAVE_DOS_PATHS           0
#define HAVE_INLINE_ASM          0
#define HAVE_MIPSFPU             0
#define HAVE_MACH_ABSOLUTE_TIME  1
#define HAVE_GETHRTIME           0
#define HAVE_COMMANDLINETOARGVW  0
#define HAVE_GETMODULEHANDLE     0
#define HAVE_GETPROCESSMEMORYINFO 0
#define HAVE_GETPROCESSTIMES     0
#define HAVE_KBHIT               0
#define HAVE_PEEKNAMEDPIPE       0
#define HAVE_SETCONSOLECTRLHANDLER 0
#define HAVE_SETDLLDIRECTORY     0
#define HAVE_ATANF               1
#define HAVE_ATAN2F              1
#define HAVE_CBRT                1
#define HAVE_CBRTF               1
#define HAVE_COPYSIGN            1
#define HAVE_COSF                1
#define HAVE_ERF                 1
#define HAVE_EXP2                1
#define HAVE_EXP2F               1
#define HAVE_EXPF                1
#define HAVE_HYPOT               1
#define HAVE_ISFINITE            1
#define HAVE_ISINF               1
#define HAVE_ISNAN               1
#define HAVE_LDEXPF              1
#define HAVE_LLRINT              1
#define HAVE_LLRINTF             1
#define HAVE_LOG10F              1
#define HAVE_LOG2                1
#define HAVE_LOG2F               1
#define HAVE_LRINT               1
#define HAVE_LRINTF              1
#define HAVE_POWF                1
#define HAVE_RINT                1
#define HAVE_ROUND               1
#define HAVE_ROUNDF              1
#define HAVE_SINF                1
#define HAVE_TRUNC               1
#define HAVE_TRUNCF              1
#define CONFIG_AVUTIL            1
#define CONFIG_AVCODEC           1
#define CONFIG_AVFORMAT          1
#define CONFIG_AVDEVICE          1
#define CONFIG_AVFILTER          1
#define CONFIG_SWRESAMPLE        1
#define CONFIG_SWSCALE           1
#define CONFIG_QSV               0
#define CONFIG_VAAPI             0
#define CONFIG_VDPAU             0
#define CONFIG_METHOD_HW_DEVICE_CTX 0
#define CONFIG_METHOD_HW_FRAMES_CTX 0
#define CONFIG_GPL               0
#define CONFIG_GPLV3             0
#define CONFIG_LGPLV3            1
#define CONFIG_NONFREE           0
#define CONFIG_THIS_YEAR         2023
#define CONFIG_LINUX_PERF        0
#define CONFIG_MACOS_KPERF       0
#define ASSERT_LEVEL             0
#define HAVE_LIB_CONFIG_H        0
#define HAVE_VALGRIND_VALGRIND_H 0
#define HAVE_OPENCL              0
#define HAVE_STRUCT_POLLFD       1

#endif /* FFMPEG_CONFIG_H */
CONFIGEOF

# Also place in libavutil/ so relative includes from internal headers work
cp "${PREFIX}/include/config.h" "${PREFIX}/include/libavutil/config.h"

echo "✅ Build Successful! Files in ${PREFIX}"
