#!/bin/bash
# 1. Patch version.sh to NOOP
cat << 'INNER_EOF' > src/ffmpeg/ffbuild/version.sh
#!/bin/bash
cat << 'H_EOF' > "\$2"
/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v6.0-takefive"
#endif /* AVUTIL_FFVERSION_H */
H_EOF
INNER_EOF
chmod +x src/ffmpeg/ffbuild/version.sh

# 2. Patch pkgconfig_generate.sh to NOOP
cat << 'INNER_EOF' > src/ffmpeg/ffbuild/pkgconfig_generate.sh
#!/bin/bash
shortname=\$1
name=lib\${shortname}
fullname=\${name}
cat << 'H_EOF' > \$name/\$fullname.pc
Name: \$fullname
Description: \$2
Version: 6.0
Libs: -L\${libdir} -l\${fullname#lib}
Cflags: -I\${includedir}
H_EOF
mkdir -p doc/examples/pc-uninstalled
cat << 'H_EOF' > doc/examples/pc-uninstalled/\${name}-uninstalled.pc
Name: \$fullname
H_EOF
INNER_EOF
chmod +x src/ffmpeg/ffbuild/pkgconfig_generate.sh

# 3. Disconnect version.sh from Makefile
sed -i '' 's/\$(M)\$(VERSION_SH) \$(SRC_PATH) libavutil\/ffversion.h \$(EXTRA_VERSION)/\$(Q)echo "#define FFMPEG_VERSION \\"v6.0-takefive\\"" > libavutil\/ffversion.h/g' src/ffmpeg/Makefile

# 4. Disconnect pkgconfig generate logic
sed -i '' 's/\$\$(M) \$\$(SRC_PATH)\/ffbuild\/pkgconfig_generate.sh \$(NAME) "\$(DESC)"/\$\$(Q)echo "" > \$\$@/g' src/ffmpeg/ffbuild/library.mak
