#!/bin/bash
# 1. Pre-generate ffversion.h so it exists before make runs (robust fallback for all FFmpeg versions)
mkdir -p src/ffmpeg/libavutil
cat > src/ffmpeg/libavutil/ffversion.h << 'EOF'
/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1-takefive"
#endif /* AVUTIL_FFVERSION_H */
EOF

# 2. Patch version.sh to NOOP (writes the same header to $2 if make ever calls it)
cat << 'INNER_EOF' > src/ffmpeg/ffbuild/version.sh
#!/bin/bash
cat << 'H_EOF' > "\$2"
/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1-takefive"
#endif /* AVUTIL_FFVERSION_H */
H_EOF
INNER_EOF
chmod +x src/ffmpeg/ffbuild/version.sh

# 3. Patch pkgconfig_generate.sh to NOOP
cat << 'INNER_EOF' > src/ffmpeg/ffbuild/pkgconfig_generate.sh
#!/bin/bash
shortname=\$1
name=lib\${shortname}
fullname=\${name}
cat << 'H_EOF' > \$name/\$fullname.pc
Name: \$fullname
Description: \$2
Version: 7.1
Libs: -L\${libdir} -l\${fullname#lib}
Cflags: -I\${includedir}
H_EOF
mkdir -p doc/examples/pc-uninstalled
cat << 'H_EOF' > doc/examples/pc-uninstalled/\${name}-uninstalled.pc
Name: \$fullname
H_EOF
INNER_EOF
chmod +x src/ffmpeg/ffbuild/pkgconfig_generate.sh

# 4. Disconnect pkgconfig generate logic
if [[ "$(uname)" == "Darwin" ]]; then
  sed -i '' 's/\$\$(M) \$\$(SRC_PATH)\/ffbuild\/pkgconfig_generate.sh \$(NAME) "\$(DESC)"/\$\$(Q)echo "" > \$\$@/g' src/ffmpeg/ffbuild/library.mak
else
  sed -i 's/\$\$(M) \$\$(SRC_PATH)\/ffbuild\/pkgconfig_generate.sh \$(NAME) "\$(DESC)"/\$\$(Q)echo "" > \$\$@/g' src/ffmpeg/ffbuild/library.mak
fi
